name: audacious
base: core22
adopt-info: audacious
grade: stable
confinement: strict
compression: lzo
architectures:
  - build-on: amd64
  - build-on: armhf
  - build-on: arm64
  
layout:
  /usr/lib/audacious:
    symlink: $SNAP/usr/lib/audacious

slots:
  audaious:
    interface: dbus
    bus: session
    name: org.atheme.audacious 
  mpris:
    name: audacious 
  
apps:
  audacious:
    command: usr/bin/audacious
    extensions: [gnome]
    common-id: org.atheme.audacious
    desktop: usr/share/applications/audacious.desktop
    plugs:
      - home
      - audio-playback
      - bluez
      - network-status
      - network
      - network-bind
      - optical-drive
      - removable-media
      - unity7
      - screen-inhibit-control
    slots:
      - mpris 
      
parts:
  fdk:
    plugin: autotools
    source: https://downloads.sourceforge.net/opencore-amr/fdk-aac-2.0.2.tar.gz
    autotools-configure-parameters:
      - --prefix=/usr 
      - --disable-static
    prime:
      - -usr/include
      - -usr/lib/pkgconfig
      - -usr/lib/*/pkgconfig
          
  ffmpeg:
    plugin: autotools
    source: https://ffmpeg.org/releases/ffmpeg-6.0.tar.xz
    source-checksum: sha256/57be87c22d9b49c112b6d24bc67d42508660e6b718b3db89c44e47e289137082
    after: [fdk]
    autotools-configure-parameters:
      - --prefix=/usr
      - --libdir=/usr/lib/$CRAFT_ARCH_TRIPLET
      - --disable-debug
      - --disable-doc
      - --disable-static
      - --enable-gpl
      - --enable-shared
      - --disable-ffplay
      - --disable-devices
      - --enable-gnutls
      - --enable-libmp3lame
      - --enable-libvorbis
      - --enable-libfdk-aac
      - --enable-nonfree
    build-packages:
      - nasm
      - libgnutls28-dev
      - libmp3lame-dev
      - libvorbis-dev
    stage-packages:
      - libmp3lame0
    prime:
      - -usr/lib/pkgconfig
      - -usr/lib/*/pkgconfig
      - -usr/share/bug
      - -usr/share/doc
      - -usr/share/lintian
      - -usr/share/pkgconfig
      - -usr/share/man
      - -usr/share/X11
      - -usr/share/alsa
      - -usr/include
      - -etc
      - -var  
  
  audacious:
    source: https://github.com/audacious-media-player/audacious.git
    source-tag: audacious-4.3.1
    parse-info: [contrib/audacious.appdata.xml]
    after: [ffmpeg]
    plugin: autotools
    autotools-configure-parameters:
      - --prefix=/usr
      - --enable-gtk3
      - --disable-qt
      - --with-buildstamp='Snapcraft' 
    override-pull: |
      craftctl default
      sed -e 's|Icon=audacious|Icon=${SNAP}/usr/share/icons/hicolor/scalable/apps/audacious.svg|' -i audacious.desktop
    override-stage: |
      craftctl default
      sed -i -e '/^plugin_dir=/s/\${exec_prefix}/\/usr/' usr/lib/pkgconfig/audacious.pc  
    stage-packages:
      - libcue2
      - liblirc-client0
      - libadplug-2.3.3-0
      - libbinio1v5
      - libsdl2-2.0-0
      - libxss1
      - libdecor-0-0
      - libfluidsynth3
      - libinstpatch-1.0-2
      - libcddb2
      - libcdio19
      - libcdio-cdda2
      - libopusfile0
      - libsndio7.0
      - libmms0
      - libneon27
    prime:
      - -usr/lib/*/libswscale.so*
      - -usr/lib/*/libavfilter.so*
      - -usr/lib/*/libavformat.so*
      - -usr/lib/*/libavcodec.so*
      - -usr/lib/*/libavutil.so*
      - -usr/lib/*/libswresample.so*
      - -usr/lib/*/libfdk*
      - -usr/lib/*/libwayland*
      - -usr/lib/libopusurl*
      - -usr/lib/*/libirrecord*
      - -usr/lib/*/liblirc.so*
      - -usr/lib/*/liblirc_driver.so*
      - -usr/lib/libfdk*
      - -usr/lib/pkgconfig
      - -usr/lib/*/pkgconfig
      - -usr/share/bug
      - -usr/share/doc
      - -usr/share/lintian
      - -usr/share/pkgconfig
      - -usr/share/man
      - -usr/share/X11
      - -usr/share/alsa
      - -usr/include
      - -etc
      - -var
      - -lib
      
  audacious-plugins:
    after: [audacious]
    source: https://github.com/audacious-media-player/audacious-plugins.git 
    source-tag: audacious-plugins-4.3.1
    plugin: meson
    meson-parameters:
      - -Dprefix=/usr
      - -Dgtk3=true
      - -Dqt=false
    build-packages:
      - libcdio-dev
      - libcdio-cdda-dev
      - libcdio++-dev
      - libcddb2-dev
      - libadplug-dev
      - oggfwd
      - oggz-tools
      - vorbisgain
      - libopus-dev
      - libopusfile-dev
      - libflac-dev
      - libfluidsynth-dev
      - libmpg123-dev
      - libwavpack-dev
      - libcue-dev
      - libspa-0.2-dev
      - libneon27-dev
      - libmms-dev
      - libmodplug1
      - libopenmpt0
      - libopenmpt-modplug1
      - libsidplayfp6
      - libbs2b0
      - libsoxr0
      - libsoxr-lsr0
      - liblirc-dev
    prime:
      - -usr/lib/pkgconfig
      - -usr/lib/*/pkgconfig
      - -usr/share/bug
      - -usr/share/lintian
      - -usr/share/pkgconfig
      - -usr/share/man
      - -usr/share/X11
      - -usr/share/alsa
      - -usr/include
      - -etc
      - -var  
      
  cleanup:
    after:  
      - audacious-plugins
    plugin: nil
    build-snaps: 
      - gnome-42-2204
      - core22
      - gtk-common-themes
    override-prime: |
      set -eux
      for snap in "gnome-42-2204" "core22" "gtk-common-themes"; do
          cd "/snap/$snap/current" && find . -type f,l -exec rm -f "$CRAFT_PRIME/{}" \;
      done    
