name: audacious
base: core22
adopt-info: audacious
grade: stable
confinement: strict
compression: lzo
architectures:
  - build-on: amd64
  - build-on: armhf
  - build-on: arm64

layout:
  /usr/lib/audacious:
    symlink: $SNAP/usr/lib/audacious

slots:
  audacious:
    interface: dbus
    bus: session
    name: org.atheme.audacious
  mpris:
    name: audacious

apps:
  audacious:
    command: usr/bin/audacious
    extensions: [gnome]
    environment:
      DISABLE_WAYLAND: 1
    common-id: org.atheme.audacious
    desktop: usr/share/applications/audacious.desktop
    plugs:
      - home
      - audio-playback
      - bluez
      - network-status
      - network
      - network-bind
      - optical-drive
      - removable-media
      - unity7
      - screen-inhibit-control
    slots:
      - mpris

parts:
  ffmpeg:
    plugin: autotools
    source: https://ffmpeg.org/releases/ffmpeg-7.0.tar.gz
    autotools-configure-parameters:
      - --prefix=/usr
      - --libdir=/usr/lib/$CRAFT_ARCH_TRIPLET
      - --disable-debug
      - --disable-doc
      - --disable-static
      - --enable-gpl
      - --enable-shared
      - --disable-ffplay
      - --disable-devices
      - --enable-gnutls
      - --enable-libmp3lame
      - --enable-libvorbis
      - --enable-libfdk-aac
      - --enable-nonfree
    build-packages:
      - nasm
      - libmp3lame-dev
      - libvorbis-dev
      - libfdk-aac-dev
    prime:
      - -usr/lib/*/pkgconfig
      - -usr/share/ffmpeg/examples
      - -usr/include

  audacious:
    source: https://github.com/audacious-media-player/audacious.git
    source-tag: audacious-4.3.1
    parse-info: [contrib/audacious.appdata.xml]
    after: [ffmpeg]
    plugin: autotools
    autotools-configure-parameters:
      - --prefix=/usr
      - --enable-gtk3
      - --disable-qt
      - --enable-libarchive
      - --with-buildstamp='Snapcraft'
    override-pull: |
      craftctl default
      sed -e 's|Icon=audacious|Icon=${SNAP}/usr/share/icons/hicolor/scalable/apps/audacious.svg|' -i audacious.desktop
    override-stage: |
      craftctl default
      sed -i -e '/^plugin_dir=/s/\${exec_prefix}/\/usr/' usr/lib/pkgconfig/audacious.pc
    build-packages:
      - libarchive-dev
    prime:
      - -usr/include
      - -usr/lib/pkgconfig

  audacious-plugins:
    after: [audacious]
    source: https://github.com/audacious-media-player/audacious-plugins.git
    source-tag: audacious-plugins-4.3.1
    plugin: meson
    meson-parameters:
      - -Dprefix=/usr
      - -Dgtk3=true
      - -Dqt=false
      - -Dalsa=false
      - -Dfilewriter=false
      - -Dpipewire=false
      - -Djack=false
      - -Dsndio=false
      - -Doss=false
      - -Dqtaudio=false
      - -Dcoreaudio=false
    build-snaps:
      - cmake
    build-packages:
      - libcdio-dev
      - libcdio-cdda-dev
      - libcdio++-dev
      - libcddb2-dev
      - libadplug-dev
      - oggfwd
      - oggz-tools
      - vorbisgain
      - libopus-dev
      - libopusfile-dev
      - libflac-dev
      - libfluidsynth-dev
      - libmpg123-dev
      - libwavpack-dev
      - libcue-dev
      - libspa-0.2-dev
      - libneon27-dev
      - libmms-dev
      - libmodplug1
      - libopenmpt0
      - libopenmpt-modplug1
      - libsidplayfp6
      - libbs2b0
      - libsoxr0
      - libsoxr-lsr0
      - liblirc-dev
      - libmp3lame-dev
      - libfaad-dev
      - libsamplerate0-dev
    prime:
      - -usr/include
      - -usr/lib/pkgconfig
      - -usr/lib/*/pkgconfig

  deps:
    after: [audacious-plugins]
    plugin: nil
    stage-packages:
      - libcue2
      - liblirc-client0
      - libadplug-2.3.3-0
      - libbinio1v5
      - libsdl2-2.0-0
      - libxss1
      - libdecor-0-0
      - libfluidsynth3
      - libinstpatch-1.0-2
      - libcddb2
      - libcdio19
      - libcdio-cdda2
      - libopusfile0
      - libmms0
      - libneon27
      - libfaad2
      - libsamplerate0
      - libfdk-aac2
      - libmp3lame0
    prime:
      - usr/lib
      - -usr/lib/*/libswscale*
      - -usr/lib/*/libavfilter*
      - -usr/lib/*/libavformat*
      - -usr/lib/*/libavcodec*
      - -usr/lib/*/libavutil*
      - -usr/lib/*/libswresample*
      - -usr/lib/*/libwayland*
      - -usr/lib/libopusurl*
      - -usr/lib/*/libirrecord*
      - -usr/lib/*/liblirc.so*
      - -usr/lib/*/liblirc_driver.so*
      - -usr/lib/*/libfaad_drm.so*
      - -usr/lib/pkgconfig
      - -usr/lib/*/pkgconfig
      - -usr/lib/*/pulseaudio
      - -usr/lib/X11

  cleanup:
    after:
      - deps
    plugin: nil
    build-snaps:
      - gnome-42-2204
      - core22
      - gtk-common-themes
    override-prime: |
      set -eux
      for snap in "gnome-42-2204" "core22" "gtk-common-themes"; do
          cd "/snap/$snap/current" && find . -type f,l -exec rm -f "$CRAFT_PRIME/{}" \;
      done
