name: audacious
base: core22
adopt-info: audacious
summary: Lightweight Open Source Music player
description: |
  Audacious is a Lightweight Gtk + Music Player.
grade: stable
confinement: strict
compression: lzo
architectures:
  - build-on: amd64
  - build-on: armhf
  - build-on: arm64
  
layout:
  /usr/lib/audacious:
    symlink: $SNAP/usr/lib/audacious


slots:
  audaious:
    interface: dbus
    bus: session
    name: org.atheme.audacious 
  mpris:
    name: audacious 
  
  
apps:
  audacious:
    command: usr/bin/audacious
    extensions: [gnome]
    common-id: org.atheme.audacious
    desktop: usr/share/applications/audacious.desktop
    plugs:
      - home
      - audio-playback
      - audio-record
      - bluez
      - bluetooth-control
      - media-control
      - network-status
      - network
      - network-bind
      - raw-usb
      - optical-drive
      - removable-media
      - unity7
      - screen-inhibit-control
    slots:
      - mpris 
      
parts:
  audacious:
    source: https://github.com/audacious-media-player/audacious.git
    after: [ffmpeg]
    plugin: meson
    meson-parameters:
       - -Dprefix=/snap/audacious/current/usr
       - -Dgtk3=true
       - -Dqt=false
       - -Dbuildstamp='Snapcraft'
    override-pull: |
      craftctl default
      craftctl set version=$(git describe --tags --abbrev=0)
    build-packages:
      - curl
      - build-essential
      - make
      - git
      - autotools-dev
      - automake
      - autoconf
      - autopoint
      - libtool
      - libtool-bin
          
    stage-packages:
      - libcue2
      - liblirc-client0
      - liblirc0
      - libadplug-2.3.3-0
      - libbinio1v5
      - libsdl2-2.0-0
      - libxss1
      - libdecor-0-0
      - libfluidsynth3
      - libinstpatch-1.0-2
      - libcddb2
      - libcdio19
      - libcdio-cdda2
      - libopusfile0
      - libpipewire-0.3-0
      - libsndio7.0
      - libmms0
      - libneon27
      - libfaad2
    organize:
      snap/audacious/current/usr: usr
    
    
  audacious-plugins:
    after: [audacious]
    source: https://github.com/audacious-media-player/audacious-plugins.git 
    plugin: meson
    meson-parameters:
       - -Dprefix=usr
       - -Dgtk3=true
       - -Dqt=false
    build-packages:
      - curl
      - build-essential
      - make
      - git
      - autotools-dev
      - automake
      - autoconf
      - autopoint
      - libtool
      - libtool-bin    
      - libcdio19
      - libcdio-utils
      - libcdio-dev
      - libcdio-cdda2
      - libcdio-cdda-dev
      - libcdio++-dev
      - libcdio++1
      - libcddb2
      - libcddb2-dev
      - libadplug-2.3.3-0
      - libadplug-dev
      - adplug-utils
      - oggfwd
      - oggz-tools
      - vorbisgain
      - xmms2-plugin-all
      - libopus-dev
      - libopus0
      - libopusfile-dev
      - libopusfile0
      - opus-tools
      - flac
      - libflac++-dev
      - libflac++6v5
      - libflac-dev
      - libflac8
      - fluidsynth
      - libfluidsynth-dev
      - libfluidsynth3
      - libmpg123-0
      - libmpg123-dev
      - wavpack
      - libwavpack-dev
      - libwavpack1
      - libcue2
      - libcue-dev
      - libpipewire-0.3-0
      - libpipewire-0.3-common
      - libpipewire-0.3-dev
      - libpipewire-0.3-modules
      - libspa-0.2-bluetooth
      - libspa-0.2-dev
      - libspa-0.2-jack
      - libspa-0.2-modules
      - libneon27
      - libneon27-dev
      - libgtk2.0-dev
      - libgtk2.0-0
      - libgtk2.0-bin
      - libgtk2.0-cil
      - libgtk2.0-cil-dev 
      - libmms0
      - libmms-dev
      - libmodplug1
      - libopenmpt0
      - libopenmpt-modplug1
      - libsidplayfp6
      - libbs2b0
      - libsamplerate0
      - libsoxr0
      - libsoxr-lsr0
      - lirc
      - libfaad-dev
      - liblirc-client0
      - liblirc0
      - liblirc-dev
      - pulseaudio-module-lirc
      - lirc-x
      - lirc-drv-irman
      - libaudcore5
   
  ffmpeg:
    # WORKAROUND:
    # Build from source because the ffmpeg package installs libraries as dependencies
    # that conflict with the Gnome extension
    plugin: autotools
    source: https://ffmpeg.org/releases/ffmpeg-6.0.tar.xz
    source-checksum: sha256/57be87c22d9b49c112b6d24bc67d42508660e6b718b3db89c44e47e289137082
    autotools-configure-parameters:
      # WORKAROUND: Install to /usr instead of /usr/local because it's not in search paths
      - --prefix=/usr
      - --disable-debug
      - --disable-doc
      - --disable-static
      - --enable-avcodec
      - --enable-gpl
      - --enable-shared
      - --disable-ffplay
      - --disable-devices
      - --enable-gnutls
      - --enable-libmp3lame
      - --enable-libvorbis
      - --enable-avformat  
      - --enable-libaom
      - --enable-swresample
      - --enable-libfdk-aac
      - --enable-nonfree
    build-packages:
      - nasm
      - libgnutls28-dev
      - libfdk-aac-dev
      - libmp3lame-dev
      - libavformat-dev
      - libvorbis-dev
      - libavcodec-dev
      - libaom-dev
      - libswresample-dev
    stage-packages:
      - libmp3lame0
      - libaom3
      - libfdk-aac2
    stage:
      - -usr/include 
    
      
      
      
     
   
   
