name: audacious
base: core22
adopt-info: audacious
grade: stable
confinement: strict
compression: lzo
architectures:
  - build-on: amd64
  - build-on: armhf
  - build-on: arm64

layout:
  /usr/lib/audacious:
    symlink: $SNAP/usr/lib/audacious

slots:
  audacious:
    interface: dbus
    bus: session
    name: org.atheme.audacious
  mpris:
    name: audacious

apps:
  audacious:
    command: usr/bin/audacious
    extensions: [gnome]
    environment:
      DISABLE_WAYLAND: 1
    common-id: org.atheme.audacious
    desktop: usr/share/applications/audacious.desktop
    plugs:
      - home
      - audio-playback
      - bluez
      - network-status
      - network
      - network-bind
      - removable-media
      - unity7
      - screen-inhibit-control
    slots:
      - mpris

parts:
  ffmpeg:
    plugin: autotools
    source: https://ffmpeg.org/releases/ffmpeg-7.0.tar.gz
    autotools-configure-parameters:
      - --prefix=/usr
      - --libdir=/usr/lib/$CRAFT_ARCH_TRIPLET
      - --disable-debug
      - --disable-doc
      - --disable-static
      - --enable-gpl
      - --enable-shared
      - --disable-ffplay
      - --disable-devices
      - --enable-gnutls
      - --enable-libmp3lame
      - --enable-libvorbis
      - --enable-libfdk-aac
      - --enable-nonfree
      - --enable-libopus
    build-packages:
      - nasm
      - libmp3lame-dev
      - libvorbis-dev
      - libfdk-aac-dev
      - libopus-dev
    prime:
      - -usr/lib/*/pkgconfig
      - -usr/share/ffmpeg/examples
      - -usr/include

  audacious:
    source: https://github.com/audacious-media-player/audacious.git
    source-depth: 1
    source-tag: 'audacious-4.3.1'
    parse-info: [contrib/audacious.appdata.xml]
    after: [ffmpeg]
    plugin: autotools
    autotools-configure-parameters:
      - --prefix=/usr
      - --enable-gtk3
      - --disable-qt
      - --enable-libarchive
      - --with-buildstamp='Snapcraft'
    override-pull: |
      craftctl default
      sed -e 's|Icon=audacious|Icon=${SNAP}/usr/share/icons/hicolor/scalable/apps/audacious.svg|' -i audacious.desktop
    override-stage: |
      craftctl default
      sed -i -e '/^plugin_dir=/s/\${exec_prefix}/\/usr/' usr/lib/pkgconfig/audacious.pc
    build-packages:
      - libarchive-dev
    prime:
      - -usr/include
      - -usr/lib/pkgconfig

  audacious-plugins:
    after: [audacious]
    source: https://github.com/audacious-media-player/audacious-plugins.git
    source-tag: 'audacious-plugins-4.3.1'
    source-depth: 1
    plugin: meson
    meson-parameters:
      - -Dprefix=/usr
      - -Dgtk3=true
      - -Dqt=false
      - -Dalsa=false
      - -Dfilewriter=false
      - -Dpipewire=false
      - -Djack=false
      - -Dsndio=false
      - -Doss=false
      - -Dqtaudio=false
      - -Dcoreaudio=false
      - -Dcdaudio=false
      - -Dlirc=false
      - -Dsid=false
      - -Dampache=false
      - -Dcue=false
      - -Dadplug=false
      - -Dopenmpt=false
      - -Dsndfile=false
      - -Dmodplug=false
      - -Dmms=false
      - -Dsoxr=false
      - -Dbs2b=false
    build-packages:
      - oggfwd
      - oggz-tools
      - vorbisgain
      - libopus-dev
      - libopusfile-dev
      - libflac-dev
      - libmpg123-dev
      - libwavpack-dev
      - libneon27-dev
      - libfaad-dev
      - libsamplerate0-dev
      - cmake
    prime:
      - -usr/include
      - -usr/lib/pkgconfig
      - -usr/lib/*/pkgconfig

  deps:
    after: [audacious-plugins]
    plugin: nil
    stage-packages:
      - libxss1
      - libdecor-0-0
      - libopusfile0
      - libneon27
      - libfaad2
      - libsamplerate0
      - libfdk-aac2
      - libmp3lame0
      - libmpg123-0
      - libvorbis0a
      - libflac8
      - libogg0
      - vorbisgain
      - libwavpack1
    prime:
      - usr/lib/*/libbinio*
      - usr/lib/*/libXss*
      - usr/lib/*/libdecor*
      - usr/lib/libopus*
      - usr/lib/*/libopus*
      - usr/lib/*/libneon*
      - usr/lib/*/libfaad*
      - usr/lib/*/libsamplerate*
      - usr/lib/*/libfdk-aac*
      - usr/lib/*/libmp3lame*
      - usr/lib/*/libmpg123*
      - usr/lib/*/libvorbis*
      - usr/lib/*/libFLAC*
      - usr/lib/*/libogg*
      - usr/bin/vorbisgain
      - usr/lib/*/libwavpack*
      - -usr/lib/*/libfaad_drm*
      - -usr/lib/libopusurl*
